// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type AuditLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Action    string
	Details   []byte
	CreatedAt pgtype.Timestamptz
}

type OauthConnection struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	AccessToken    pgtype.Text
	RefreshToken   pgtype.Text
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	Subdomain   pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectConfig struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	AuthType             string
	DatabaseType         string
	DatabaseUrl          string
	Port                 pgtype.Int4
	ContainerID          pgtype.Text
	EnvironmentVariables []byte
	Features             []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type UsageMetric struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Date          pgtype.Date
	ApiCalls      pgtype.Int4
	DatabaseSize  pgtype.Int8
	BandwidthUsed pgtype.Int8
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Name          pgtype.Text
	PasswordHash  pgtype.Text
	EmailVerified pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserAuthMethod struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	AuthType   string
	Identifier string
	Verified   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
}
